### ISSUE TITLE
Fremdriftsplan

### ISSUE THREAD

**Issue by Jaknil** [robotikklinja/cnc-dreiebenk#1]
Deres prosjekt består av en masse trinn, jeg trur det kan vara lurt å lage en liste øver ting som må gjøres og prøve å sette dem i en logisk rekkefølge. Jeg opplever at det er enklest å starte planlegge fra målet og gå i trinn bakover.  Når dere har laget en liste med alle del-oppgaver som skall gjøres i en rekkefølge så kan dere velge rimelige uke-mål.

**Comment by HiroTachii** [comment]
Laget en enkel liste over ting som må gjøres, er det noen flere ting du ser med det første?

**Comment by Jaknil** [comment]
Bare at jeg rekommanderer dere å bruke planen for å finne ut når dere kommer å trenge hvilket utstyr så at vi kan bestille det før dere trenger det. Til eksempel tre eller aluminiumsplater i spesifikk tykkelse for fresing.
