### ISSUE TITLE
Skyvelære

### ISSUE THREAD

**Issue by MartinRobotikk** [robotikklinja/cnc-dreiebenk#2]
Hadde vært fint med nye gode skyvelære, helst digitale.
https://nettbutikk.wuerth.no/haandverktoy/maaleverktoy-og-merkeverktoy/skyvelaere-2/skyvelaere-digitalt

**Comment by Jaknil** [comment]
Nå har jeg lagt inn behovsmelding og fått kvittert at de nå er bestilt fra Wurth. 

Jeg bestillte 4 stk til 1ELR og 4 stk til 2ELR.
